### ISSUE TITLE
Does not work with Nova Essex

### ISSUE THREAD

**Issue by bastichelaar** [griddynamics/nova-billing#1]
In Nova Essex (E3) it gives the following error:

```
(nova_billing.amqp_listener): TRACE: Traceback (most recent call last):
(nova_billing.amqp_listener): TRACE:   File "/usr/local/lib/python2.7/dist-packages/nova_billing-0.0.2-py2.7.egg/nova_billing/amqp.py", line 100, in process_message
(nova_billing.amqp_listener): TRACE:     self.process_event(body, message)
(nova_billing.amqp_listener): TRACE:   File "/usr/local/lib/python2.7/dist-packages/nova_billing-0.0.2-py2.7.egg/nova_billing/amqp.py", line 116, in process_event
(nova_billing.amqp_listener): TRACE:     "project_id": body["args"]["request_spec"]
(nova_billing.amqp_listener): TRACE: KeyError: 'request_spec'
(nova_billing.amqp_listener): TRACE:
```

It looks like the body contents have changed into:

```
{u'instance_uuid': u'1a08b4db-0d13-4c0b-9fa7-d90b1d181e77', u'filter_properties': {u'scheduler_hints': {}}, u'requested_networks': None, u'admin_password': u'PASSWORD', u'injected_files': []}
```

**Comment by rlz** [comment]
We support only Diablo release. Essex will be supported later, when we release our essex build. But it should pass all our test first and we should apply all out diablo extensions first.

If you have a patch, which will allow nova-billing to work with both 'essex' and 'diablo' releases we can apply it.

**Comment by bastichelaar** [comment]
FYI, I forked the repository to work with Essex. See https://github.com/30loops/nova-billing for the details.
